# Generated by Django 5.0.6 on 2024-07-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_complaint_status'),
        ('complaint', '0002_alter_user_gender'),
    ]

    operations = [
    ]
